### ISSUE TITLE
赞,有个疑问

### ISSUE THREAD

**Issue by dadpp** [GangWang/letapm#1]
over

**Comment by wlevene** [comment]
这些是服务器后台需要做的运算，业务逻辑并不是很复杂，也还好。

**Comment by BaiCanLin** [comment]
这些都是客户端实现提交给服务器的,目前实现了大部分,有一些不是很明白里面的逻辑

**Comment by wlevene** [comment]
你的思路好像不太对，   这个问题不是这个代码相关的问题，我先关掉了。;)
