### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dadpp** [GangWang/letapm#2]
malloc_error_break 这个试着调试一下 发现为 nil

**Comment by wlevene** [comment]
这看起好像是内存不足引起分配失败，你可以再提供一些信息，是否一起动app，第一次执行到这个必然出现？或者检查一下是否有其它模块在一直分配内存，还比如xcode的nszombie这个东西有时也会引起这个问题。

我刚才也测试了一下，没出现这个问题
![15f5e270-72a3-464c-be95-bb41d097a2a1](https://cloud.githubusercontent.com/assets/1000877/18829891/fd8925c2-8410-11e6-967c-1a729b1ba203.png)

(此库在日活近千万的app中使用过半年，很少出过问题，应该不会有太大问题，稳定性应该还可以的)

**Comment by BaiCanLin** [comment]
内置了听云，友盟等SDK，但是去掉这些第三方还是奔溃，百思不得姐，然后我主要注释掉 NSURLSessionDataTask *task = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error)  这个方法，就不会奔溃，我是使用这个来发送网络情的，后来我查看了我们的网络请求貌似使用了 MKNetworkKit 我在排除是不是这个引起的

**Comment by dadpp** [comment]
这个问题是由于都修改自 FLEX 的库，里面如果没有使用上传下载是不会奔溃的，经过我测试，原因是里面回调的 block 没有添加 copy，导致的内存泄漏问题，研究了一个通宵解决了。

**Comment by wlevene** [comment]
赞~ 辛苦！      这个bug我需要修改代码吗?

**Comment by dadpp** [comment]
![image](https://cloud.githubusercontent.com/assets/8268339/18898941/b4281c46-8567-11e6-9ace-38350beafac1.png)

你测测 这里 ➕个 copy 就不会奔溃的了

**Comment by dadpp** [comment]
https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/interactions-page    抓包了数据大概是下面这样的
![image](https://cloud.githubusercontent.com/assets/8268339/18944971/d70f33b8-865a-11e6-8227-ec181d353575.png)
你有了解过zh这方面的吗，这些是怎么组合的参数，我看OneAPM等都是跟他的参数一样的

**Comment by wlevene** [comment]
之前研究过，现在有点记不清楚了， 我们是自己定义的格式   **分类/类名/方法名/参数1/参数2/参数3...**  
分类是自己做的分类，将网络和视图与其它类做了枚举

**Comment by dadpp** [comment]
对的，但是有很多类型，Image，Database，Json,ViewLoading,Network ,WebView 共 6 类 一般都是这几类的，你有知道哪一些开源的有做这方面的吗

**Comment by wlevene** [comment]
你收下邮件

**Comment by dadpp** [comment]
如何 Swizzling Implementation socket，我看你的库是改了 CocoaAsyncSocket 的类名，☺️
